set nobackup
set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4
set nowrap
set number
set relativenumber
set cursorline
syntax on
set termguicolors
colorscheme catppuccin_mocha
set mouse=a
