set nobackup
set autoindent
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
set nowrap
set number
set relativenumber
set cursorline
syntax on
set termguicolors
colorscheme catppuccin_mocha
set mouse=a
set incsearch
set ignorecase
set smartcase
